language: node_js
node_js:
  - 10
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - npm i -g yarn@latest
  - npm i -g makeshift && makeshift -s @plasma-ui -r registry.npmjs.org
install:
  - yarn
script:
  - yarn test
  - yarn run build
deploy:
  provider: npm
  edge: true # opt in to dpl v2
  email: $NPM_EMAIL
  api_key:
    secure: $NPM_TOKEN
  on:
    repo: plasma-ui/plasma-ui
    branch: production
